# Generated by Django 5.0.7 on 2024-07-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='previous_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
