# Generated by Django 5.0.7 on 2024-07-24 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_planning', '0002_plan_current_balance_plan_previous_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
